apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: sproud
build:
  artifacts:
  - image: ghcr.io/getsproud/authentication
    context: ./services/authentication
    sync:
      manual:
      - src: src/**/*.*
        dest: .
    docker:
      target: builder
  - image: ghcr.io/getsproud/company
    context: ./services/company
    sync:
      manual:
      - src: src/**/*.*
        dest: .
    docker:
      target: builder
  - image: ghcr.io/getsproud/employee
    context: ./services/employee
    sync:
      manual:
      - src: src/**/*.*
        dest: .
    docker:
      target: builder
  - image: ghcr.io/getsproud/gateway
    context: ./services/gateway
    sync:
      manual:
      - src: src/**/*.*
        dest: .
    docker:
      target: builder
  - image: ghcr.io/getsproud/training
    context: ./services/training
    sync:
      manual:
      - src: src/**/*.*
        dest: .
    docker:
      target: builder
  - image: ghcr.io/getsproud/category
    context: ./services/category
    sync:
      manual:
      - src: src/**/*.*
        dest: .
    docker:
      target: builder
  - image: ghcr.io/getsproud/budget
    context: ./services/budget
    sync:
      manual:
      - src: src/**/*.*
        dest: .
    docker:
      target: builder
  - image: ghcr.io/getsproud/feedback
    context: ./services/feedback
    sync:
      manual:
      - src: src/**/*.*
        dest: .
    docker:
      target: builder
  - image: ghcr.io/getsproud/brownbag
    context: ./services/brownbag
    sync:
      manual:
      - src: src/**/*.*
        dest: .
    docker:
      target: builder
  - image: ghcr.io/getsproud/department
    context: ./services/department
    sync:
      manual:
      - src: src/**/*.*
        dest: .
    docker:
      target: builder
  - image: ghcr.io/getsproud/email
    context: ./services/email
    sync:
      manual:
      - src: src/**/*.*
        dest: .
    docker:
      target: builder
  - image: ghcr.io/getsproud/app
    context: ./services/app
    sync:
      manual:
      - src: src/**/*.*
        dest: .
      - src: public/**/*.*
        dest: .
      - src: test/**/*.*
        dest: .
    docker:
      network: bridge
      target: develop
  tagPolicy:
    sha256: {}
  local: {}
deploy:
  kubectl:
    manifests:
      - helm-rendered.yaml
profiles:
  - name: stage
    patches:
      - op: replace
        path: /build/artifacts/0/docker/
        value: production
      - op: replace
        path: /build/artifacts/1/docker/
        value: production
      - op: replace
        path: /build/artifacts/2/docker/
        value: production
      - op: replace
        path: /build/artifacts/3/docker/
        value: production
      - op: replace
        path: /build/artifacts/4/docker/
        value: production
      - op: replace
        path: /build/artifacts/5/docker/
        value: production
      - op: replace
        path: /build/artifacts/6/docker/
        value: production
      - op: replace
        path: /build/artifacts/7/docker/
        value: production
      - op: replace
        path: /build/artifacts/8/docker/
        value: production
      - op: replace
        path: /build/artifacts/9/docker/
        value: production
      - op: replace
        path: /build/artifacts/10/docker/
        value: production
      - op: replace
        path: /build/artifacts/11/docker/
        value: production
